name: yav
on: [push, pull_request]
jobs:

  format:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Format
        run: |
          sudo apt update
          sudo apt install clang-format -y
          ./format.sh -c

  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          sudo apt update
          sudo apt install cmake build-essential git libdrm-dev -y
          cmake -Bbuild .
          cmake --build build
          pushd build
          ctest
          ./yav --help
          popd
